#!/usr/bin/bash
lock_entry="🔒\tLock"
suspend_entry="🌙\tSuspend"
reboot_entry="🔄\tReboot"
poweroff_entry="💀\tPoweroff"
logout_entry="🚪\tLogout"
entries="$lock_entry\n$suspend_entry\n$reboot_entry\n$poweroff_entry\n$logout_entry"

choice=$(printf "%b" "$entries" | rofi -dmenu -p "Power:" -i -format i -matching fuzzy)
case "$choice" in
  0) hyprlock ;;
  1) systemctl suspend ;;
  2) systemctl reboot ;;
  3) systemctl poweroff ;;
  4) hyprctl dispatch exit ;;
esac
